version: 0.0
os: linux
files:
  - source: /files/etc/app_protect/conf/AppProtectDefaultPolicy.json
    destination: /etc/app_protect/conf/
  - source: /files/etc/app_protect/conf/log_all.json
    destination: /etc/app_protect/conf/
  - source: /files/etc/nginx/nginx.conf
    destination: /etc/nginx/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_server
      timeout: 300
      runas: root