name: Release Initial Repo
on:
  push:
    branches:
      - master
jobs:
  s3-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release Initial Repo to S3
      run: bash scripts/pipeline/release_repo.sh ${{secrets.AWS_ACCESS_KEY_ID}} ${{secrets.AWS_SECRET_ACCESS_KEY}} ${{secrets.AWS_S3_INITIAL_REPO_BUCKET}} ${{secrets.AWS_S3_INITIAL_REPO_OBJECT}}